openapi: 3.0.0
info:
  title: Blog API Project
  version: 1.0.0
  description: Tài liệu API BE2 cho dự án blog của nhóm 15
servers:
  - url: http://localhost:5000
    description: Development
  - url: https://xdpm-web-be2.onrender.com
    description: Main server
  - url: https://nhom15-chieu-t6-ku61.onrender.com
    description: Test server


#Authorize and Roles    
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  # ==========================================
  # 1. USERS API
  # ==========================================

#lấy token
  /users/login:
    post:
      summary: Đăng nhập cho để lấy token ADMIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: "Email của tài khoản"
                  example: "admin@example.com"
                password:
                  type: string
                  description: "Mật khẩu"
                  example: "123456"
      responses:
        200:
          description: Đăng nhập thành công, trả về JWT Token
        401:
          description: Sai mật khẩu
        404:
          description: Email không tồn tại

  /users:
    get:
      summary: Lấy danh sách tất cả người dùng
      tags: [Users]
      responses:
        200:
          description: Trả về danh sách thành công
    post:
      summary: Tạo người dùng mới
      tags: [Users]
      requestBody:               
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:          
                  type: string
                name:
                  type: string
                role:
                  type: string
                  description: "Nhập 'admin' nếu muốn tạo tài khoản quản trị"
                bio:
                  type: string
                location:
                  type: string
      responses:
        201:
          description: Tạo thành công
        400:
          description: Lỗi dữ liệu
  /users/{id}:
    get:
      summary: Lấy chi tiết người dùng theo ID
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Thành công
    put:
      summary: Cập nhật thông tin người dùng
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                passwordHash:
                  type: string
                name:
                  type: string
                bio:
                  type: string
                avatar:
                  type: string
                location:
                  type: string
      responses:
        200:
          description: Cập nhật thành công
        404:
          description: Không tìm thấy người dùng
    delete:
      summary: Xóa người dùng
      tags: [Users]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Xóa thành công
        404:
          description: Không tìm thấy người dùng

 
  # ==========================================
  # 2. POSTS API
  # ==========================================
  /posts:
    get:
      summary: Lấy danh sách tất cả bài viết
      tags: [Posts]
      responses:
        200:
          description: Thành công
    post:
      summary: Tạo một bài viết mới
      tags: [Posts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authorId:
                  type: string
                  description: "ID của tác giả (Lấy từ bảng Users)"
                title:
                  type: string
                slug:
                  type: string
                  description: "Đường dẫn URL (VD: top-10-tips)"
                content:
                  type: string
                coverImage:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                status:
                  type: string
                  enum: [published, draft, pending]
                  default: published
                visibility:
                  type: string
                  enum: [public, private]
                  default: public
      responses:
        201:
          description: Tạo bài viết thành công

  /posts/{id}:
    get:
      summary: Lấy chi tiết bài viết
      tags: [Posts]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Thành công
    put:
      summary: Cập nhật bài viết
      tags: [Posts]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                slug:
                  type: string
                content:
                  type: string
                coverImage:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                status:
                  type: string
                  enum: [published, draft, pending]
                visibility:
                  type: string
                  enum: [public, private]
      responses:
        200:
          description: Cập nhật thành công
    delete:
      summary: Xóa mềm bài viết
      tags: [Posts]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Xóa thành công

  # ==========================================
  # 3. COMMENTS API
  # ==========================================
  /comments:
    get:
      summary: Lấy danh sách tất cả bình luận (Admin)
      tags: [Comments]
      responses:
        200:
          description: Thành công
    post:
      summary: Thêm một bình luận mới
      tags: [Comments]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  description: "ID của bài viết đang được bình luận"
                authorId:
                  type: string
                  description: "ID của người đang bình luận"
                parentId:
                  type: string
                  description: "ID của bình luận gốc (Nếu đây là câu trả lời/reply. Để trống nếu là bình luận mới)"
                content:
                  type: string
                  description: "Nội dung bình luận"
      responses:
        201:
          description: Bình luận thành công

  /comments/{id}:
    delete:
      summary: Xóa bình luận (Admin)
      tags: [Comments]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Xóa thành công
  # ==========================================
  # 4. ADMIN API
  # ==========================================
  /admin/stats:
    get:
      summary: Xem thống kê hệ thống (Chỉ Admin)
      tags: [Admin]
      security:            
        - bearerAuth: []
      responses:
        200:
          description: Trả về dữ liệu thống kê
        403:
          description: Không có quyền truy cập
  /admin/users/{id}/ban:
    put:
      summary: Khóa tài khoản người dùng (Admin)
      tags: [Admin]
      security:             
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Đã khóa thành công

  /admin/users/{id}/unban:
    put:
      summary: Mở khóa tài khoản (Admin)
      tags: [Admin]
      security:             
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Đã mở khóa thành công        